name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add private NuGet source
      run: dotnet nuget add source --username TimPaasche --password ${{ secrets.NUGET_AUTH_TOKEN }} --store-password-in-clear-text --name private-repo https://github.com/TimPaasche/tex-to-typst-DotNet.git
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
